(defun is-at-last-col ()
        (interactive)
        (save-excursion
                (end-of-line)
                (setq last-col (current-column))
                )
        (setq was-at-last-col 0)
        (if (eq last-col (current-column))
                        (setq was-at-last-col 1)
                )
        )

(define-key evil-visual-state-map (kbd "C-x") 'evil-delete)
        ;; (lambda ()
                ;; (interactive)
                ;; (call-interactively 'evil-delete)
                ;; (call-interactively 'esc)
                ;; ))
;; (global-set-key (kbd "C-c") 'evil-yank)

;; following lines required to work in evil-emacs-mode
;; (define-key evil-normal-state-map (kbd "C-c") 'evil-yank)
;; (define-key evil-normal-state-map (kbd "C-x") 'evil-delete)
;; evil-ex-completion-map for in search-replace
(define-key evil-ex-completion-map (kbd "C-v") 'my-paste-after-0)
;; (key "C-S-c" 'evil-yank)
(key "C-S-c" 'my-yank-0)
(key "C-M-c" 'evil-delete)
;; (define-key evil-normal-state-map (kbd "C-x") 'my-paste-after-0)
;; (define-key evil-emacs-state-map (kbd "C-x") 'my-paste-after-0)
;; (define-key evil-insert-state-map (kbd "C-x") 'my-paste-after-0)
(key "C-y" 'undo-tree-redo)
(key "C-z" 'undo-tree-undo)

;; (key "C-c" 'my-yank-line-0)
(define-key evil-visual-state-map (kbd "C-c") 'my-yank-line-0)
(define-key evil-emacs-state-map (kbd "C-c") 'my-yank-line-0)
(define-key evil-emacs-state-map (kbd "C-x") 'evil-delete-whole-line)
(key "C-S-v" 'my-paste-before-0)
(key "C-v" 'my-paste-after-0)

(global-set-key (kbd "C-M-s-a") 'spacemacs/copy-whole-buffer-to-clipboard)
(global-set-key (kbd "C-M-s-p") 'spacemacs/copy-clipboard-to-whole-buffer)
