(key "S-<up>" 'evil-visual-line)
(key "S-<down>" 'evil-visual-line)
(define-key evil-visual-state-map (kbd "S-<up>") 'evil-previous-line)
(define-key evil-visual-state-map (kbd "S-<down>") 'evil-next-line)
;; (global-set-key (kbd "S-<up>") 'evil-visual-line)
;; (global-set-key (kbd "S-<down>") 'evil-visual-line)

;; (global-set-key (kbd "S-<right>")
;; 								(lambda () (interactive)
;; 									(call-interactively 'evil-visual-char)
;; 									;; (setq this-command-keys-shift-translated t)
;; 									(call-interactively 'right-char)
;; 									))
(key "S-<right>" '(lambda () (interactive)
									  (call-interactively 'evil-visual-char)
									  ;; (setq this-command-keys-shift-translated t)
									  (call-interactively 'right-char)
										))
(key "S-<left>" '(lambda () (interactive)
									 (call-interactively 'evil-visual-char)
									 ;; (setq this-command-keys-shift-translated t)
									 (call-interactively 'left-char)
									 ))
(define-key evil-visual-state-map (kbd "S-<right>") 'evil-forward-char)
(define-key evil-visual-state-map (kbd "S-<left>") 'evil-backward-char)

(key "<S-end>" '(lambda () (interactive)
									(call-interactively 'evil-visual-char)
									;; (setq this-command-keys-shift-translated t)
									(call-interactively 'end-of-line)
									(call-interactively 'left-char)
									))
(key "<S-home>" '(lambda () (interactive)
									 (call-interactively 'evil-visual-char)
									 ;; (setq this-command-keys-shift-translated t)
									 (beginning-of-visual-line)
									 ))
(key "<C-S-right>" '(lambda () (interactive)
											(call-interactively 'evil-visual-char)
											;; (setq this-command-keys-shift-translated t)
											(call-interactively 'right-word)
											))
(key "<C-S-left>" '(lambda () (interactive)
										 (call-interactively 'evil-visual-char)
										 ;; (setq this-command-keys-shift-translated t)
										 (call-interactively 'left-word)
										 )
		 )

(define-key evil-visual-state-map (kbd "<C-S-right>") 'right-word)
(define-key evil-visual-state-map (kbd "<C-right>") 'right-word)
(define-key evil-visual-state-map (kbd "<up>") 'previous-line)
(define-key evil-visual-state-map (kbd "<down>") 'next-line)
;; (define-key evil-visual-state-map (kbd "<C-right>")
;; (lambda ()
;; (save-excursion
;; (right-word)
;; ()
;; ))
(define-key evil-visual-state-map (kbd "<C-S-left>") 'left-word)
(define-key evil-visual-state-map (kbd "<C-left>") 'left-word)

(define-key evil-visual-state-map (kbd "<C-S-left>") 'evil-visual-state-map)
(define-key evil-visual-state-map (kbd "<C-S-right>") 'evil-visual-state-map)

(define-key evil-visual-state-map (kbd "<home>") 'beginning-of-visual-line)
(define-key evil-visual-state-map (kbd "<end>") 'end-of-visual-line)
